name: 'Sign Guestbook'
author: Lewis Lloyd <lewis_lloyd@live.co.uk>
description: 'Keep a live guestbook in a README through issues.'
branding:
  icon: 'edit-3'  
  color: 'green'
inputs:
  user:
    description: The issue creator, used as the signatory.
    required: true
  message: 
    description: The issue's title, used as the signatory's message.
    required: true
runs:
  using: 'node12'
  main: 'dist/index.js'
  args:
    - ${{ inputs.user }}
    - ${{ inputs.message }}
